### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by GeerFrz** [Nafees10/qui#10]
When I type special characters (such as á é ñ) in any input widget, they don't appear with the correct encoding. I am using linux, and utf-8 encoding on my terminals (gnome-terminal, guake).

@adamdruppe

**Comment by adamdruppe** [comment]
so i looked at the code and it looks like a lot of dchars are casted to char in qui, that is likely what is breaking this.

**Comment by Nafees10** [comment]
@Geer1159 can you check if the last commit (8e4564f ) fixes this.  
  
I have some special characters on my keyboard (¹,²,³,€,½,¾,ł,¶, ...) and those seem to be working (although I'm not sure why, as the widgets still store them in char[]).

**Comment by Nafees10** [comment]
Commit 319be16 should fix this as all widgets now use `dchar` and `dstring`.
