### ISSUE TITLE
Rounding errors in layouts

### ISSUE THREAD

**Issue by jakobkogler** [Nafees10/qui#14]
Hey. I've been playing a little bit with `qui`, and noticed a bug concerning layouts.

When the screen with is 101 pixel, and you have two widgets in a horizontal layout, both widgets get the width 50. Which means there is one pixel spare.
This can have nasty effects. E.g. if you hide one of the widgets, making the other widget taking 100% of the width, and then show the hidden widget again. Characters that were drawn in the 100% mode in column 101 will not be erased.

![animation](https://user-images.githubusercontent.com/7143573/102674055-e487c380-4194-11eb-87c0-73a2ff54480e.gif)

The problem is in the `recalculateWidgetsSize(QLayout.Type T)` method of the `QLayout` class and the `ratioToRaw` function. It just rounds down the float value (`selectedRatio / ratioTotal * total`). A typical solution to this problem is to round some of the values up. Usually the values with the highest remainder. So to round one of the two widgets up to size 51, and the other one down to size 50. E.g. see here: [round_preserve_sum](http://larmarange.github.io/JLutils/reference/round_preserve_sum.html).

**Comment by Nafees10** [comment]
Thanks for letting me know. commit 8799be8 should fix this, I'll put a release out soon

**Comment by Nafees10** [comment]
This should be fixed in `qui 0.5.2`.

**Comment by jakobkogler** [comment]
Thanks. Already tried the new version. Works perfectly.
